name: Fetch and Push PKC Honeypot logs

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  download-and-commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download 14-day log file
      run: |
        curl -o IOCs/network-indicators/honeypot/iocs-14d.csv https://honey.pkc.supreme.sh/pkc/ssh/logs/honey-14d.log

    - name: Download 30-day log file
      run: |
        curl -o IOCs/network-indicators/honeypot/iocs-30d.csv https://honey.pkc.supreme.sh/pkc/ssh/logs/honey-30d.log

    - name: Commit and push if there are changes
      run: |
        git config --global user.name 'Cam [Actions]'
        git config --global user.email 'cam@pkc.mozmail.com'
        git add IOCs/network-indicators/honeypot/iocs-14d.csv IOCs/network-indicators/honeypot/iocs-30d.csv
        git diff --staged --quiet || git commit -m "Update Honeypot IOC files"
        git push || echo "No changes to commit"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
